services:
  postgres:
    container_name: postgresDB
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "myDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "321"
      PG_DATA: "/var/lib/postgresql/data"
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - net

  spring:
    container_name: spring
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    networks:
      - net
    depends_on:
      - postgres

networks:
  net:
    driver: bridge
volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./DockerData